### ISSUE TITLE
There is NO code  :-(

### ISSUE THREAD

**Issue by steveculshaw** [michaelstephensonuk/IntegrationPlaybook-DataTransformationModeller#1]
There is NO code  :-(

**Comment by michaelstephensonuk** [comment]
Hi Steve,

Sorry ive been too busy with work to finish getting this all published and out there.

Got a bit of spare time now so catching up on stuff and code is now added.

Hope you have had a great xmas and are keeping well

All the best
Mike

**Comment by steveculshaw** [comment]
Many thanks Mike

Thanks for all the hard work you do in the UK (& world) integration arena

Cheers,
SteveC.

**Comment by michaelstephensonuk** [comment]
thanks steve much appreciated, love to hear what you think of the tool
